/* ═══════════════════════════════════════════════════════════════════
   dotes.js — Dotes D&D 5e / 5.5e
   Fuentes: PHB 2024 (origen, generales, estilos de lucha, dones épicos) ·
            PHB 2014 · Xanathar's (XGtE) · Tasha's (TCE) · Fizban's (FTD) ·
            Strixhaven (SCC)
   Nombres en inglés · Descripciones en español.
   Las dotes que existen en 2014 y 2024 con efectos casi idénticos van en una
   sola entrada "[PHB 2024 / TCE]"; las que cambiaron mucho se separan en
   "[PHB 2024]" y "[PHB 2014]".
   Campos: n (nombre), tipo (grupo del desplegable), d (texto),
     a  = cómo se usa en combate (lo lee el panel de Acciones):
          "A" Acción · "B" Acción Adicional · "R" Reacción · "O" otro/sin acción
          (combinable: "BR"). Sin a = dote pasiva.
     alias = nombres antiguos de la dote: las fichas guardadas con ellos
          siguen reconociéndose.
═══════════════════════════════════════════════════════════════════ */

const DND_DOTES = [

  /* ════════════════════════════════
     DOTES DE ORIGEN (PHB 2024) — se obtienen con el trasfondo (Nv.1) o más tarde como dote general
  ════════════════════════════════ */
  { n:"Alert [PHB 2024]", tipo:"Origen", a:"O", alias:["Alert [PHB'24]"], d:"Competencia en iniciativa: sumas tu bonificador de competencia a las tiradas de iniciativa. Intercambio de iniciativa: justo después de tirar iniciativa puedes intercambiar tu resultado con el de un aliado voluntario del mismo combate (ninguno de los dos puede estar Incapacitado)." },
  { n:"Crafter [PHB 2024]", tipo:"Origen", alias:["Crafter [PHB'24]"], d:"Competencia con 3 Herramientas de Artesano de la tabla de Fabricación Rápida. Descuento: 20 % al comprar objetos no mágicos. Fabricación Rápida: al terminar un Descanso Largo, si tienes las herramientas y la competencia, creas 1 objeto de equipo de la tabla; dura hasta tu siguiente Descanso Largo." },
  { n:"Healer [PHB 2024]", tipo:"Origen", a:"A", alias:["Healer [PHB'24]"], d:"Médico de Batalla: con un Botiquín de Sanador, gastas 1 uso y realizas la acción Utilizar sobre una criatura a 5 pies: esa criatura gasta 1 Dado de Golpe, tú lo tiras y recupera PG iguales al resultado + tu bonificador de competencia. Repetir curación: al tirar dados para restaurar PG con esta dote o con un conjuro, puedes repetir cada 1 y usar la nueva tirada." },
  { n:"Lucky [PHB 2024]", tipo:"Origen", a:"O", alias:["Lucky [PHB'24]"], d:"Puntos de Suerte = tu bonificador de competencia (los recuperas todos con un Descanso Largo). Ventaja: al hacer una Prueba de d20, gastas 1 punto para tener Ventaja. Desventaja: cuando una criatura te hace una tirada de ataque, gastas 1 punto para imponerle Desventaja." },
  { n:"Magic Initiate [PHB 2024]", tipo:"Origen", alias:["Magic Initiate [PHB'24]"], d:"Eliges la lista de Clérigo, Druida o Mago. Aprendes 2 trucos y 1 conjuro de nivel 1 de esa lista; el de nivel 1 siempre está preparado y puedes lanzarlo 1 vez sin espacio por Descanso Largo (o con espacios). Característica de lanzamiento: INT, SAB o CAR. Al subir de nivel puedes cambiar un conjuro de la dote por otro del mismo nivel de la lista. Repetible con listas distintas." },
  { n:"Musician [PHB 2024]", tipo:"Origen", a:"O", alias:["Musician [PHB'24]"], d:"Competencia con 3 Instrumentos Musicales. Canción Alentadora: al terminar un Descanso Corto o Largo puedes tocar un instrumento con el que seas competente y dar Inspiración Heroica a tantos aliados que te oigan como tu bonificador de competencia." },
  { n:"Savage Attacker [PHB 2024]", tipo:"Origen", alias:["Savage Attacker [PHB'14 / PHB'24]"], d:"Una vez por turno, al impactar con un arma, tiras los dados de daño del arma dos veces y usas el resultado que prefieras. [2014: sólo ataques cuerpo a cuerpo y se volvía a tirar el daño.]" },
  { n:"Skilled [PHB 2024]", tipo:"Origen", alias:["Skilled [PHB'14 / PHB'24]"], d:"Ganas competencia en 3 habilidades o herramientas a tu elección. Repetible. [2014: mismo efecto; no repetible.]" },
  { n:"Tavern Brawler [PHB 2024]", tipo:"Origen", alias:["Tavern Brawler [PHB'24]"], d:"Golpe Desarmado mejorado: tu Golpe Desarmado puede infligir daño contundente igual a 1d4 + mod. FUE en lugar del daño normal. Repetir daño: si sacas 1 en un dado de daño de tu Golpe Desarmado, repites ese dado y usas el nuevo resultado. Empujón: una vez por turno, al impactar con un Golpe Desarmado como parte de la acción Atacar, además del daño empujas al objetivo 5 pies. Competencia con armas improvisadas." },
  { n:"Tough [PHB 2024]", tipo:"Origen", alias:["Tough [PHB'14 / PHB'24]"], d:"Tus PG máximos aumentan en el doble de tu nivel al obtener la dote y en 2 más cada vez que subes de nivel. [2014: dote general con el mismo efecto.]" },

  /* ════════════════════════════════
     DOTES GENERALES (PHB 2024) — requieren nivel 4+
  ════════════════════════════════ */
  { n:"Ability Score Improvement [PHB 2024]", tipo:"General", alias:["Ability Score Improvement [PHB'14 / PHB'24]"], d:"Req. Nv.4+. Aumentas una característica en 2, o dos características en 1 cada una (máx. 20). Repetible. [2014: era una opción de la clase, no una dote.]" },
  { n:"Actor [PHB 2024]", tipo:"General", alias:["Actor [PHB'24]"], d:"Req. Nv.4+, CAR 13+. +1 CAR (máx. 20). Imitación: Ventaja en pruebas de CAR (Engaño o Interpretación) para hacerte pasar por otra persona. Mimetismo: puedes copiar sonidos y voces de criaturas; quien los oiga hace una prueba de SAB (Perspicacia) CD 8 + mod. CAR + comp. para detectar la imitación." },
  { n:"Athlete [PHB 2024]", tipo:"General", alias:["Athlete [PHB'24]"], d:"Req. Nv.4+, FUE o DES 13+. +1 FUE o DES (máx. 20). Velocidad de trepar igual a tu Velocidad. Levantarte estando Tumbado sólo cuesta 5 pies de movimiento. Saltos de longitud o altura con sólo 5 pies de carrerilla." },
  { n:"Charger [PHB 2024]", tipo:"General", alias:["Charger [PHB'24]"], d:"Req. Nv.4+, FUE o DES 13+. +1 FUE o DES (máx. 20). Al realizar la acción Correr, tu Velocidad aumenta 10 pies durante esa acción. Ataque en carga: si te mueves al menos 10 pies en línea recta hacia un objetivo justo antes de impactarlo con un ataque cuerpo a cuerpo durante la acción Atacar, una vez por turno infliges +1d8 de daño o lo empujas hasta 10 pies (si es como mucho un tamaño mayor que tú)." },
  { n:"Chef [PHB 2024 / TCE]", tipo:"General", a:"B", alias:["Chef [TCE / PHB'24]"], d:"Req. Nv.4+ (PHB 2024). +1 CON o SAB (máx. 20). Competencia con Utensilios de Cocinero. Comida reconstituyente: durante un Descanso Corto cocinas para hasta 4 + comp. criaturas; quienes gasten Dados de Golpe al final del descanso recuperan 1d8 PG extra. Golosinas: en 1 hora o en un Descanso Largo preparas tantas golosinas como tu bonificador de competencia; comerse una es una Acción Adicional y da PG temporales iguales a tu bonificador de competencia; duran 8 horas. [TCE 2014: mismo efecto, sin requisito de nivel.]" },
  { n:"Crossbow Expert [PHB 2024]", tipo:"General", alias:["Crossbow Expert [PHB'24]"], d:"Req. Nv.4+, DES 13+. +1 DES (máx. 20). Ignoras la propiedad Carga de las ballestas de mano, ligera y pesada. Disparar en cuerpo a cuerpo: no sufres Desventaja al atacar a distancia con ballesta a 5 pies de un enemigo. Doble arma: al hacer el ataque adicional de la propiedad Ligera con una ballesta que la tenga, añades tu modificador de característica a su daño." },
  { n:"Crusher [PHB 2024 / TCE]", tipo:"General", alias:["Crusher [PHB'24]","Crusher [TCE]"], d:"Req. Nv.4+ (PHB 2024). +1 FUE o CON (máx. 20). Empujón: una vez por turno, al impactar con un ataque que inflige daño contundente, mueves al objetivo 5 pies a un espacio libre (si es como mucho un tamaño mayor que tú). Crítico: al causar un crítico con daño contundente, las tiradas de ataque contra esa criatura tienen Ventaja hasta el inicio de tu siguiente turno." },
  { n:"Defensive Duelist [PHB 2024]", tipo:"General", a:"R", alias:["Defensive Duelist [PHB'24]"], d:"Req. Nv.4+, DES 13+. +1 DES (máx. 20). Parada: si empuñas un arma de Finura y una criatura te impacta con un ataque cuerpo a cuerpo, puedes usar tu Reacción para sumar tu bonificador de competencia a tu CA contra ese ataque, pudiendo hacerlo fallar." },
  { n:"Dual Wielder [PHB 2024]", tipo:"General", a:"B", alias:["Dual Wielder [PHB'24]"], d:"Req. Nv.4+, FUE o DES 13+. +1 FUE o DES (máx. 20). Combate con dos armas mejorado: si atacas con un arma Ligera durante la acción Atacar, puedes hacer un ataque extra con Acción Adicional con un arma cuerpo a cuerpo distinta que no tenga A Dos Manos (no añades tu modificador al daño, salvo que sea negativo). Desenfundado rápido: sacas o guardas dos armas sin A Dos Manos en lugar de una." },
  { n:"Durable [PHB 2024]", tipo:"General", a:"B", alias:["Durable [PHB'24]"], d:"Req. Nv.4+. +1 CON (máx. 20). Burlar a la Muerte: Ventaja en salvaciones de muerte. Recuperación Rápida: como Acción Adicional gastas 1 Dado de Golpe, lo tiras y recuperas PG iguales al resultado." },
  { n:"Elemental Adept [PHB 2024]", tipo:"General", alias:["Elemental Adept [PHB'24]"], d:"Req. Nv.4+, rasgo Lanzamiento de Conjuros o Magia de Pacto. +1 INT, SAB o CAR (máx. 20). Maestría Elemental: eliges Ácido, Frío, Fuego, Relámpago o Trueno; tus conjuros ignoran la Resistencia a ese tipo y, al tirar su daño, puedes tratar cada 1 como 2. Repetible con tipos distintos. [2014: sin ASI.]" },
  { n:"Fey-Touched [PHB 2024 / TCE]", tipo:"General", a:"B", alias:["Fey Touched [TCE / PHB'24]"], d:"Req. Nv.4+ (PHB 2024). +1 INT, SAB o CAR (máx. 20). Magia Feérica: aprendes Misty Step y 1 conjuro de nivel 1 de Adivinación o Encantamiento a tu elección; siempre preparados; puedes lanzar cada uno 1 vez por Descanso Largo sin espacio (o con espacios). Característica de lanzamiento: la que aumentaste. [TCE 2014: igual, sin requisito de nivel.]" },
  { n:"Grappler [PHB 2024]", tipo:"General", alias:["Grappler [PHB'24]"], d:"Req. Nv.4+, FUE o DES 13+. +1 FUE o DES (máx. 20). Golpear y agarrar: al impactar con un Golpe Desarmado durante la acción Atacar, puedes aplicar a la vez el daño y el agarre (una vez por turno). Ventaja de ataque: Ventaja en ataques contra una criatura que tengas agarrada. Luchador veloz: mover a una criatura agarrada de tu tamaño o menor no te cuesta movimiento adicional." },
  { n:"Great Weapon Master [PHB 2024]", tipo:"General", a:"B", alias:["Great Weapon Master [PHB'24]"], d:"Req. Nv.4+, FUE 13+. +1 FUE (máx. 20). Maestría con Armas Pesadas: al impactar con un arma Pesada durante la acción Atacar en tu turno, infliges daño extra igual a tu bonificador de competencia. Hender: justo después de causar un crítico o reducir a 0 PG a una criatura con un arma cuerpo a cuerpo, puedes hacer un ataque con esa misma arma como Acción Adicional. [2014: –5 al ataque para +10 al daño con armas Pesadas.]" },
  { n:"Heavily Armored [PHB 2024]", tipo:"General", alias:["Heavily Armored [PHB'24]"], d:"Req. Nv.4+, Entrenamiento con Armadura Media. +1 FUE o CON (máx. 20). Entrenamiento con Armadura Pesada." },
  { n:"Heavy Armor Master [PHB 2024]", tipo:"General", alias:["Heavy Armor Master [PHB'24]"], d:"Req. Nv.4+, Entrenamiento con Armadura Pesada. +1 FUE o CON (máx. 20). Reducción de daño: mientras llevas armadura pesada, el daño contundente, perforante y cortante que sufres de un ataque se reduce en tu bonificador de competencia." },
  { n:"Inspiring Leader [PHB 2024]", tipo:"General", a:"O", alias:["Inspiring Leader [PHB'24]"], d:"Req. Nv.4+, SAB o CAR 13+. +1 SAB o CAR (máx. 20). Actuación Estimulante: al terminar un Descanso Corto o Largo puedes dar una actuación de hasta 10 minutos que inspire hasta 6 aliados (incluido tú) que te vean u oigan: cada uno gana PG temporales iguales a tu nivel + mod. de la característica aumentada." },
  { n:"Keen Mind [PHB 2024]", tipo:"General", a:"B", alias:["Keen Mind [PHB'24]"], d:"Req. Nv.4+, INT 13+. +1 INT (máx. 20). Estudio Guiado: eliges Arcana, Historia, Investigación, Naturaleza o Religión; ganas competencia (o Pericia si ya la tienes). Estudio Rápido: realizas la acción Estudiar como Acción Adicional." },
  { n:"Lightly Armored [PHB 2024]", tipo:"General", alias:["Lightly Armored [PHB'14 / PHB'24]"], d:"Req. Nv.4+. +1 FUE o DES (máx. 20). Entrenamiento con Armadura Ligera y Escudos." },
  { n:"Mage Slayer [PHB 2024]", tipo:"General", a:"O", alias:["Mage Slayer [PHB'24]"], d:"Req. Nv.4+. +1 FUE o DES (máx. 20). Rompe-concentración: cuando dañas a una criatura que se concentra, tiene Desventaja en la salvación para mantener la concentración. Mente Protegida: si fallas una salvación de INT, SAB o CAR, puedes tener éxito en su lugar; no puedes volver a hacerlo hasta un Descanso Corto o Largo. [2014: ataque de reacción contra lanzadores adyacentes y Ventaja en salvaciones contra sus conjuros.]" },
  { n:"Martial Weapon Training [PHB 2024]", tipo:"General", alias:["Martial Weapon Training [PHB'24]"], d:"Req. Nv.4+. +1 FUE o DES (máx. 20). Competencia con las armas Marciales." },
  { n:"Medium Armor Master [PHB 2024]", tipo:"General", alias:["Medium Armor Master [PHB'24]"], d:"Req. Nv.4+, Entrenamiento con Armadura Media. +1 FUE o DES (máx. 20). Portador Diestro: con armadura media sumas 3 (en vez de 2) a tu CA si tu DES es 16 o más." },
  { n:"Moderately Armored [PHB 2024]", tipo:"General", alias:["Moderately Armored [PHB'24]"], d:"Req. Nv.4+, Entrenamiento con Armadura Ligera. +1 FUE o DES (máx. 20). Entrenamiento con Armadura Media." },
  { n:"Mounted Combatant [PHB 2024]", tipo:"General", alias:["Mounted Combatant [PHB'24]"], d:"Req. Nv.4+. +1 FUE, DES o SAB (máx. 20). Golpe Montado: montado, tienes Ventaja en ataques contra criaturas no montadas a 5 pies de tu montura que sean al menos un tamaño menor que ella. Salto Lateral: si tu montura debe hacer una salvación de DES para sufrir la mitad de daño, no sufre ninguno si la supera y sólo la mitad si la falla. Desvío: montado, puedes hacer que un ataque que impacta a tu montura te impacte a ti en su lugar (si no estás Incapacitado)." },
  { n:"Observant [PHB 2024]", tipo:"General", a:"B", alias:["Observant [PHB'24]"], d:"Req. Nv.4+, INT o SAB 13+. +1 INT o SAB (máx. 20). Observador Atento: eliges Investigación, Percepción o Perspicacia; ganas competencia (o Pericia si ya la tienes). Búsqueda Rápida: realizas la acción Buscar como Acción Adicional." },
  { n:"Piercer [PHB 2024 / TCE]", tipo:"General", alias:["Piercer [PHB'24]","Piercer [TCE]"], d:"Req. Nv.4+ (PHB 2024). +1 FUE o DES (máx. 20). Perforar: una vez por turno, al impactar con un ataque que inflige daño perforante, puedes repetir uno de los dados de daño y usar el nuevo resultado. Crítico: al causar un crítico con daño perforante, tiras un dado de daño adicional." },
  { n:"Poisoner [PHB 2024 / TCE]", tipo:"General", a:"B", alias:["Poisoner [PHB'24]","Poisoner [TCE]"], d:"Req. Nv.4+ (PHB 2024). +1 DES o INT (máx. 20). Veneno Potente: tus ataques que infligen daño de veneno ignoran la Resistencia a él. Elaborar Veneno: competencia con el Kit de Envenenador; con 1 hora y 50 po creas tantas dosis como tu bonificador de competencia. Aplicar una dosis a un arma o munición es una Acción Adicional y dura 1 minuto o hasta que inflija daño; el objetivo impactado hace una salvación de CON (CD 8 + mod. de la característica aumentada + comp.) o sufre 2d8 de daño de veneno y queda Envenenado hasta el final de tu siguiente turno. [TCE 2014: CD 14 fija.]" },
  { n:"Polearm Master [PHB 2024]", tipo:"General", a:"BR", alias:["Polearm Master [PHB'24]"], d:"Req. Nv.4+, FUE o DES 13+. +1 FUE o DES (máx. 20). Golpe con el Asta: tras la acción Atacar con un bastón, lanza o arma con Pesada y Alcance, usas una Acción Adicional para atacar con el extremo opuesto (1d4 contundente, mismo modificador). Ataque Reactivo: empuñando un bastón, lanza o arma con Pesada y Alcance, usas tu Reacción para hacer un ataque cuerpo a cuerpo contra una criatura que entre en tu alcance con esa arma." },
  { n:"Resilient [PHB 2024]", tipo:"General", alias:["Resilient [PHB'14 / PHB'24]"], d:"Req. Nv.4+. Eliges una característica en la que no tengas competencia en salvación: +1 a ella (máx. 20) y ganas competencia en sus salvaciones. Repetible con características distintas." },
  { n:"Ritual Caster [PHB 2024]", tipo:"General", alias:["Ritual Caster [PHB'24]"], d:"Req. Nv.4+, INT, SAB o CAR 13+. +1 INT, SAB o CAR (máx. 20). Conjuros de Ritual: eliges conjuros de nivel 1 con la etiqueta Ritual, tantos como tu bonificador de competencia; siempre preparados; puedes lanzarlos como ritual o con espacios. Cada vez que aumenta tu bonificador de competencia aprendes uno más. Ritual Rápido: puedes lanzar uno de esos conjuros de ritual con su tiempo de lanzamiento normal, sin los 10 minutos adicionales y sin gastar espacio; no puedes volver a hacerlo hasta un Descanso Largo. [2014: libro de rituales de una clase.]" },
  { n:"Sentinel [PHB 2024]", tipo:"General", a:"R", alias:["Sentinel [PHB'24]"], d:"Req. Nv.4+, FUE o DES 13+. +1 FUE o DES (máx. 20). Guardián: justo después de que una criatura a 5 pies realice la acción Retirarse o impacte a un objetivo que no seas tú, puedes hacerle un ataque de oportunidad. Detener: cuando impactas a una criatura con un ataque de oportunidad, su Velocidad pasa a 0 el resto del turno." },
  { n:"Shadow-Touched [PHB 2024 / TCE]", tipo:"General", a:"A", alias:["Shadow Touched [TCE / PHB'24]","Shadow-Touched [TCE / PHB'24]"], d:"Req. Nv.4+ (PHB 2024). +1 INT, SAB o CAR (máx. 20). Magia de las Sombras: aprendes Invisibility y 1 conjuro de nivel 1 de Ilusión o Nigromancia a tu elección; siempre preparados; puedes lanzar cada uno 1 vez por Descanso Largo sin espacio (o con espacios). Característica de lanzamiento: la que aumentaste. [TCE 2014: igual, sin requisito de nivel.]" },
  { n:"Sharpshooter [PHB 2024]", tipo:"General", alias:["Sharpshooter [PHB'24]"], d:"Req. Nv.4+, DES 13+. +1 DES (máx. 20). Ignorar Cobertura: tus ataques a distancia con arma ignoran Cobertura Media y de Tres Cuartos. Disparar en cuerpo a cuerpo: no sufres Desventaja al atacar a distancia a 5 pies de un enemigo. Tiros Largos: atacar a largo alcance no te impone Desventaja. [2014: –5 al ataque para +10 al daño.]" },
  { n:"Shield Master [PHB 2024]", tipo:"General", a:"R", alias:["Shield Master [PHB'24]"], d:"Req. Nv.4+, Entrenamiento con Escudos. +1 FUE (máx. 20). Golpe de Escudo: si atacas a una criatura a 5 pies con un ataque cuerpo a cuerpo en la acción Atacar, una vez por turno el objetivo hace una salvación de FUE (CD 8 + mod. FUE + comp.) o lo empujas 5 pies o lo derribas (Tumbado). Interponer Escudo: si superas una salvación de DES que reduce el daño a la mitad, puedes usar tu Reacción con un escudo para no sufrir daño." },
  { n:"Skill Expert [PHB 2024 / TCE]", tipo:"General", alias:["Skill Expert [TCE / PHB'24]"], d:"Req. Nv.4+ (PHB 2024). +1 a una característica a tu elección (máx. 20). Ganas competencia en 1 habilidad y Pericia en 1 habilidad en la que ya seas competente. [TCE 2014: igual, sin requisito de nivel.]" },
  { n:"Skulker [PHB 2024]", tipo:"General", alias:["Skulker [PHB'24]"], d:"Req. Nv.4+, DES 13+. +1 DES (máx. 20). Vista Ciega 10 pies. Niebla de Guerra: Ventaja en las pruebas de DES (Sigilo) de la acción Esconderse mientras estés en combate. Francotirador: si fallas una tirada de ataque estando Oculto, el ataque no revela tu posición." },
  { n:"Slasher [PHB 2024 / TCE]", tipo:"General", alias:["Slasher [PHB'24]","Slasher [TCE]"], d:"Req. Nv.4+ (PHB 2024). +1 FUE o DES (máx. 20). Desjarretar: una vez por turno, al impactar con un ataque que inflige daño cortante, reduces la Velocidad del objetivo en 10 pies hasta el inicio de tu siguiente turno. Crítico: al causar un crítico con daño cortante, el objetivo tiene Desventaja en sus tiradas de ataque hasta el inicio de tu siguiente turno." },
  { n:"Speedy [PHB 2024]", tipo:"General", alias:["Speedy [PHB'24]"], d:"Req. Nv.4+, DES o CON 13+. +1 DES o CON (máx. 20). Tu Velocidad aumenta 10 pies. Al realizar la acción Correr ignoras el Terreno Difícil el resto del turno. Los ataques de oportunidad contra ti tienen Desventaja." },
  { n:"Spell Sniper [PHB 2024]", tipo:"General", alias:["Spell Sniper [PHB'24]"], d:"Req. Nv.4+, rasgo Lanzamiento de Conjuros o Magia de Pacto. +1 INT, SAB o CAR (máx. 20). Ignorar Cobertura: tus ataques de conjuro ignoran Cobertura Media y de Tres Cuartos. Lanzar en cuerpo a cuerpo: estar a 5 pies de un enemigo no impone Desventaja a tus ataques de conjuro a distancia. Alcance aumentado: los conjuros con tirada de ataque y alcance de 10 pies o más ven su alcance aumentado en 60 pies. [2014: alcance ×2 y un truco de ataque extra.]" },
  { n:"Telekinetic [PHB 2024 / TCE]", tipo:"General", a:"B", alias:["Telekinetic [PHB'24]","Telekinetic [TCE]"], d:"Req. Nv.4+ (PHB 2024). +1 INT, SAB o CAR (máx. 20). Telequinesia Menor: aprendes Mage Hand (sin componentes verbales ni somáticos y con mano invisible; si ya lo conoces, su alcance aumenta 30 pies). Empujón Telequinético: como Acción Adicional empujas a una criatura que veas a 30 pies: salvación de FUE (CD 8 + mod. de la característica aumentada + comp.) o la mueves 5 pies hacia ti o alejándola de ti." },
  { n:"Telepathic [PHB 2024 / TCE]", tipo:"General", a:"A", alias:["Telepathic [PHB'24]","Telepathic [TCE]"], d:"Req. Nv.4+ (PHB 2024). +1 INT, SAB o CAR (máx. 20). Expresión Telepática: hablas telepáticamente a una criatura que veas a 60 pies, en un idioma que conozcas (ella no puede responder telepáticamente). Detect Thoughts: siempre preparado; lo lanzas 1 vez por Descanso Largo sin espacio (o con espacios); característica de lanzamiento: la que aumentaste." },
  { n:"War Caster [PHB 2024]", tipo:"General", a:"R", alias:["War Caster [PHB'24]"], d:"Req. Nv.4+, rasgo Lanzamiento de Conjuros o Magia de Pacto. +1 INT, SAB o CAR (máx. 20). Concentración: Ventaja en las salvaciones de CON para mantener la concentración. Conjuro Reactivo: cuando una criatura provoca tu ataque de oportunidad al salir de tu alcance, puedes usar tu Reacción para lanzarle un conjuro (tiempo de lanzamiento de 1 acción, objetivo único). Componentes Somáticos: puedes hacerlos aunque tengas armas o escudo en las manos." },
  { n:"Weapon Master [PHB 2024]", tipo:"General", alias:["Weapon Master [PHB'24]"], d:"Req. Nv.4+. +1 FUE o DES (máx. 20). Propiedad de Maestría: puedes usar la propiedad de maestría de 1 tipo de arma Simple o Marcial con el que seas competente; al terminar un Descanso Largo puedes cambiar el tipo elegido. [2014: competencia con 4 armas.]" },

  /* ════════════════════════════════
     ESTILOS DE LUCHA (PHB 2024) — requieren el rasgo Estilo de Lucha de una clase
  ════════════════════════════════ */
  { n:"Fighting Style: Archery [PHB 2024]", tipo:"Estilo de Combate", alias:["Fighting Style: Archery [PHB'24]"], d:"Req. rasgo Estilo de Lucha. +2 a las tiradas de ataque con armas a distancia." },
  { n:"Fighting Style: Blind Fighting [PHB 2024]", tipo:"Estilo de Combate", alias:["Fighting Style: Blind Fighting [PHB'24]"], d:"Req. rasgo Estilo de Lucha. Tienes Vista Ciega con alcance de 10 pies." },
  { n:"Fighting Style: Defense [PHB 2024]", tipo:"Estilo de Combate", alias:["Fighting Style: Defense [PHB'24]"], d:"Req. rasgo Estilo de Lucha. +1 a la CA mientras llevas armadura ligera, media o pesada." },
  { n:"Fighting Style: Dueling [PHB 2024]", tipo:"Estilo de Combate", alias:["Fighting Style: Dueling [PHB'24]"], d:"Req. rasgo Estilo de Lucha. +2 al daño con un arma cuerpo a cuerpo empuñada con una sola mano y sin otras armas." },
  { n:"Fighting Style: Great Weapon Fighting [PHB 2024]", tipo:"Estilo de Combate", alias:["Fighting Style: Great Weapon Fighting [PHB'24]"], d:"Req. rasgo Estilo de Lucha. Al sacar 1 o 2 en un dado de daño de un ataque con arma cuerpo a cuerpo empuñada con dos manos, lo tratas como un 3. El arma debe tener A Dos Manos o Versátil." },
  { n:"Fighting Style: Interception [PHB 2024]", tipo:"Estilo de Combate", a:"R", alias:["Fighting Style: Interception [PHB'24]"], d:"Req. rasgo Estilo de Lucha. Cuando una criatura que veas impacta a otra a 5 pies de ti con una tirada de ataque, usas tu Reacción para reducir el daño en 1d10 + tu bonificador de competencia. Debes empuñar un escudo o un arma Simple o Marcial." },
  { n:"Fighting Style: Protection [PHB 2024]", tipo:"Estilo de Combate", a:"R", alias:["Fighting Style: Protection [PHB'24]"], d:"Req. rasgo Estilo de Lucha. Cuando una criatura que veas ataca a un objetivo que no seas tú a 5 pies de ti, usas tu Reacción para imponer Desventaja a su tirada de ataque. Debes empuñar un escudo." },
  { n:"Fighting Style: Thrown Weapon Fighting [PHB 2024]", tipo:"Estilo de Combate", alias:["Fighting Style: Thrown Weapon Fighting [PHB'24]"], d:"Req. rasgo Estilo de Lucha. +2 al daño de los ataques a distancia con armas con la propiedad Arrojadiza. Puedes sacar un arma Arrojadiza como parte del ataque con ella." },
  { n:"Fighting Style: Two-Weapon Fighting [PHB 2024]", tipo:"Estilo de Combate", alias:["Fighting Style: Two-Weapon Fighting [PHB'24]"], d:"Req. rasgo Estilo de Lucha. Al hacer el ataque adicional de la propiedad Ligera, añades tu modificador de característica a su daño si no lo sumas ya." },
  { n:"Fighting Style: Unarmed Fighting [PHB 2024]", tipo:"Estilo de Combate", alias:["Fighting Style: Unarmed Fighting [PHB'24]"], d:"Req. rasgo Estilo de Lucha. Tus Golpes Desarmados infligen 1d6 + mod. FUE de daño contundente (1d8 si no empuñas armas ni escudo). Al inicio de cada uno de tus turnos puedes infligir 1d4 de daño contundente a una criatura que tengas agarrada." },

  /* ════════════════════════════════
     DONES ÉPICOS (PHB 2024) — requieren nivel 19+; +1 a una característica (máx. 30)
  ════════════════════════════════ */
  { n:"Boon of Combat Prowess [PHB 2024]", tipo:"Boon Épico", a:"O", alias:["Boon of Combat Prowess [PHB'24]"], d:"Req. Nv.19+. +1 a una característica (máx. 30). Puntería Insuperable: cuando fallas una tirada de ataque, puedes impactar en su lugar; no puedes volver a usarlo hasta el inicio de tu siguiente turno." },
  { n:"Boon of Dimensional Travel [PHB 2024]", tipo:"Boon Épico", a:"O", alias:["Boon of Dimensional Travel [PHB'24]"], d:"Req. Nv.19+. +1 a una característica (máx. 30). Pasos Parpadeantes: justo después de realizar la acción Atacar o la acción Magia, puedes teletransportarte hasta 30 pies a un espacio libre que veas." },
  { n:"Boon of Energy Resistance [PHB 2024]", tipo:"Boon Épico", a:"R", alias:["Boon of Energy Resistance [PHB'24]"], d:"Req. Nv.19+. +1 a una característica (máx. 30). Resistencias: Resistencia a 2 tipos de daño a elegir entre Ácido, Frío, Fuego, Relámpago, Necrótico, Veneno, Psíquico, Radiante y Trueno; puedes cambiar la elección al terminar un Descanso Largo. Redirección de Energía: cuando sufres daño de uno de esos tipos, puedes usar tu Reacción para obligar a una criatura que veas a 60 pies a hacer una salvación de DES (CD 8 + mod. CON + comp.); si falla, sufre daño del mismo tipo igual a 2d12 + tu mod. CON." },
  { n:"Boon of Fate [PHB 2024]", tipo:"Boon Épico", a:"O", d:"Req. Nv.19+. +1 a una característica (máx. 30). Mejorar el Destino: cuando tú u otra criatura a 60 pies que veas hace una Prueba de d20, puedes tirar 2d4 y aplicar el resultado como bonificador o penalizador a la tirada. No puedes volver a usarlo hasta que tires iniciativa o termines un Descanso Corto o Largo." },
  { n:"Boon of Fortitude [PHB 2024]", tipo:"Boon Épico", alias:["Boon of Fortitude [PHB'24]"], d:"Req. Nv.19+. +1 a una característica (máx. 30). Salud Fortificada: tus PG máximos aumentan en 40; además, una vez por turno, al recuperar PG recuperas PG adicionales iguales a tu mod. CON." },
  { n:"Boon of Irresistible Offense [PHB 2024]", tipo:"Boon Épico", alias:["Boon of Irresistible Offense [PHB'24]"], d:"Req. Nv.19+. +1 FUE o DES (máx. 30). Superar Defensas: el daño contundente, perforante y cortante que infliges ignora siempre la Resistencia. Golpe Arrollador: al sacar 20 natural en una tirada de ataque, infliges daño extra igual a la característica que aumentaste con esta dote (del mismo tipo que el ataque)." },
  { n:"Boon of Recovery [PHB 2024]", tipo:"Boon Épico", a:"B", alias:["Boon of Recovery [PHB'24]"], d:"Req. Nv.19+. +1 a una característica (máx. 30). Última Resistencia: cuando fueras a quedar a 0 PG, puedes quedar a 1 PG en su lugar y recuperar PG iguales a la mitad de tus PG máximos; 1/Descanso Largo. Recuperar Vitalidad: tienes una reserva de 10d10; como Acción Adicional gastas los dados que quieras, los tiras y recuperas PG iguales al total; la reserva se restablece con un Descanso Largo." },
  { n:"Boon of Skill [PHB 2024]", tipo:"Boon Épico", alias:["Boon of Skill [PHB'24]"], d:"Req. Nv.19+. +1 a una característica (máx. 30). Formación Universal: ganas competencia en todas las habilidades. Maestría Especializada: ganas Pericia en 1 habilidad en la que aún no la tengas." },
  { n:"Boon of Speed [PHB 2024]", tipo:"Boon Épico", a:"B", alias:["Boon of Speed [PHB'24]"], d:"Req. Nv.19+. +1 a una característica (máx. 30). Tu Velocidad aumenta 30 pies. Artista del Escape: como Acción Adicional realizas la acción Retirarse, que además pone fin a la condición Agarrado que sufras." },
  { n:"Boon of Spell Recall [PHB 2024]", tipo:"Boon Épico", a:"O", alias:["Boon of Spell Recall [PHB'24]"], d:"Req. Nv.19+, Lanzamiento de Conjuros. +1 INT, SAB o CAR (máx. 30). Lanzamiento Gratuito: cada vez que lanzas un conjuro con un espacio de nivel 1 a 4, tiras 1d4; si sale el nivel del espacio, éste no se gasta." },
  { n:"Boon of the Night Spirit [PHB 2024]", tipo:"Boon Épico", a:"B", d:"Req. Nv.19+. +1 a una característica (máx. 30). Fundirse con las Sombras: con Luz Tenue u Oscuridad, como Acción Adicional te vuelves Invisible; termina justo después de realizar una acción, Acción Adicional o Reacción. Forma de Sombra: con Luz Tenue u Oscuridad tienes Resistencia a todo el daño salvo Psíquico y Radiante." },
  { n:"Boon of Truesight [PHB 2024]", tipo:"Boon Épico", alias:["Boon of Truesight [PHB'24]"], d:"Req. Nv.19+. +1 a una característica (máx. 30). Tienes Visión Verdadera con alcance de 60 pies." },

  /* ════════════════════════════════
     DOTES DEL PHB 2014 (5e original) — sólo las que difieren de la versión 2024 o no existen en ella
  ════════════════════════════════ */
  { n:"Actor [PHB 2014]", tipo:"General (PHB 2014)", alias:["Actor [PHB'14]"], d:"+1 CAR (máx. 20). Ventaja en pruebas de CAR (Engaño) y (Interpretación) para hacerte pasar por otra persona. Puedes imitar el habla de alguien o los sonidos de una criatura tras oírlos durante al menos 1 minuto; quien lo oiga puede detectar la imitación con una prueba de SAB (Perspicacia) contra tu prueba de CAR (Engaño)." },
  { n:"Alert [PHB 2014]", tipo:"General (PHB 2014)", alias:["Alert [PHB'14]"], d:"+5 a la iniciativa. No puedes ser sorprendido mientras estés consciente. Las demás criaturas no obtienen Ventaja en sus ataques contra ti por estar ocultas." },
  { n:"Athlete [PHB 2014]", tipo:"General (PHB 2014)", alias:["Athlete [PHB'14]"], d:"+1 FUE o DES (máx. 20). Levantarte estando Tumbado sólo cuesta 5 pies de movimiento. Trepar no cuesta movimiento adicional. Haces saltos de longitud y altura con sólo 5 pies de carrerilla." },
  { n:"Charger [PHB 2014]", tipo:"General (PHB 2014)", a:"B", alias:["Charger [PHB'14]"], d:"Si realizas la acción Correr, puedes usar tu Acción Adicional para hacer un ataque cuerpo a cuerpo con arma o empujar a una criatura. Si te moviste al menos 10 pies en línea recta justo antes de esa Acción Adicional, ganas +5 al daño del ataque (si impactas) o empujas a la criatura hasta 10 pies (si lo consigues)." },
  { n:"Crossbow Expert [PHB 2014]", tipo:"General (PHB 2014)", a:"B", alias:["Crossbow Expert [PHB'14]"], d:"Ignoras la propiedad Carga de las ballestas con las que eres competente. Estar a 5 pies de un enemigo hostil no impone Desventaja a tus ataques a distancia. Si atacas con un arma de una mano en la acción Atacar, puedes usar una Acción Adicional para atacar con una ballesta de mano con la que seas competente." },
  { n:"Defensive Duelist [PHB 2014]", tipo:"General (PHB 2014)", a:"R", alias:["Defensive Duelist [PHB'14]"], d:"Req. DES 13+. Si empuñas un arma de Finura con la que seas competente y otra criatura te impacta con un ataque cuerpo a cuerpo, puedes usar tu Reacción para sumar tu bonificador de competencia a tu CA contra ese ataque, pudiendo hacerlo fallar." },
  { n:"Dual Wielder [PHB 2014]", tipo:"General (PHB 2014)", alias:["Dual Wielder [PHB'14]"], d:"+1 CA mientras empuñes un arma cuerpo a cuerpo distinta en cada mano. Puedes luchar con dos armas aunque no sean Ligeras. Puedes sacar o guardar dos armas de una mano en el momento en que sólo podrías con una." },
  { n:"Dungeon Delver [PHB 2014]", tipo:"General (PHB 2014)", alias:["Dungeon Delver [PHB'14]"], d:"Ventaja en pruebas de SAB (Percepción) e INT (Investigación) para detectar puertas secretas. Ventaja en las salvaciones para evitar trampas y Resistencia al daño que infligen. Puedes buscar trampas mientras viajas a ritmo normal." },
  { n:"Durable [PHB 2014]", tipo:"General (PHB 2014)", alias:["Durable [PHB'14]"], d:"+1 CON (máx. 20). Cuando tiras un Dado de Golpe para recuperar PG, el mínimo que recuperas es el doble de tu modificador de CON (mínimo 2)." },
  { n:"Elemental Adept [PHB 2014]", tipo:"General (PHB 2014)", alias:["Elemental Adept [PHB'14]"], d:"Req. capacidad de lanzar al menos 1 conjuro. Eliges Ácido, Frío, Fuego, Relámpago o Trueno: tus conjuros ignoran la Resistencia a ese tipo y, al tirar su daño, tratas cada 1 como 2. Repetible con tipos distintos." },
  { n:"Grappler [PHB 2014]", tipo:"General (PHB 2014)", alias:["Grappler [PHB'14]"], d:"Req. FUE 13+. Ventaja en ataques contra una criatura que tengas agarrada. Como acción puedes intentar inmovilizarla (prueba de agarre): si lo consigues, tú y ella estáis Apresados hasta que termine el agarre." },
  { n:"Great Weapon Master [PHB 2014]", tipo:"General (PHB 2014)", a:"B", alias:["Great Weapon Master [PHB'14]"], d:"Si causas un crítico o reduces a una criatura a 0 PG con un arma cuerpo a cuerpo, puedes hacer un ataque con esa arma como Acción Adicional. Antes de atacar con un arma Pesada con la que seas competente, puedes aceptar –5 a la tirada de ataque para infligir +10 de daño si impactas." },
  { n:"Healer [PHB 2014]", tipo:"General (PHB 2014)", a:"A", alias:["Healer [PHB'14]"], d:"Cuando estabilizas a una criatura con un Botiquín de Sanador, ésta recupera 1 PG. Como acción, gastas 1 uso del botiquín para que una criatura a 5 pies recupere 1d6 + 4 PG + su número de Dados de Golpe; no puede volver a beneficiarse hasta un Descanso Corto o Largo." },
  { n:"Heavily Armored [PHB 2014]", tipo:"General (PHB 2014)", alias:["Heavily Armored [PHB'14]"], d:"Req. competencia con armadura media. +1 FUE (máx. 20). Competencia con armadura pesada." },
  { n:"Heavy Armor Master [PHB 2014]", tipo:"General (PHB 2014)", alias:["Heavy Armor Master [PHB'14]"], d:"Req. competencia con armadura pesada. +1 FUE (máx. 20). Mientras llevas armadura pesada, el daño contundente, perforante y cortante de armas no mágicas se reduce en 3." },
  { n:"Inspiring Leader [PHB 2014]", tipo:"General (PHB 2014)", a:"O", alias:["Inspiring Leader [PHB'14]"], d:"Req. CAR 13+. Dedicas 10 minutos a inspirar a hasta 6 criaturas amistosas (incluido tú) a 30 pies que puedan verte y oírte: cada una gana PG temporales iguales a tu nivel + tu mod. de CAR. No pueden beneficiarse de nuevo hasta un Descanso Corto o Largo." },
  { n:"Keen Mind [PHB 2014]", tipo:"General (PHB 2014)", alias:["Keen Mind [PHB'14]"], d:"+1 INT (máx. 20). Siempre sabes dónde está el norte y cuántas horas faltan para el próximo amanecer o atardecer. Recuerdas con precisión todo lo que has visto u oído en el último mes." },
  { n:"Lightly Armored [PHB 2014]", tipo:"General (PHB 2014)", d:"+1 FUE o DES (máx. 20). Competencia con armadura ligera." },
  { n:"Linguist [PHB 2014]", tipo:"General (PHB 2014)", alias:["Linguist [PHB'14]"], d:"+1 INT (máx. 20). Aprendes 3 idiomas a tu elección. Puedes crear mensajes cifrados: quien no conozca el cifrado necesita una prueba de INT (CD = tu INT + bonificador de competencia) o magia para descifrarlos." },
  { n:"Lucky [PHB 2014]", tipo:"General (PHB 2014)", a:"O", alias:["Lucky [PHB'14]"], d:"Tienes 3 puntos de suerte (los recuperas con un Descanso Largo). Al hacer una tirada de ataque, prueba o salvación, puedes gastar 1 punto para tirar un d20 adicional y elegir cuál usar. También puedes gastar 1 punto cuando te hacen una tirada de ataque: tiras un d20 y eliges si el ataque usa el d20 del atacante o el tuyo." },
  { n:"Mage Slayer [PHB 2014]", tipo:"General (PHB 2014)", a:"R", alias:["Mage Slayer [PHB'14]"], d:"Cuando una criatura a 5 pies de ti lanza un conjuro, puedes usar tu Reacción para hacerle un ataque cuerpo a cuerpo. Cuando dañas a una criatura que se concentra, tiene Desventaja en la salvación para mantener la concentración. Ventaja en salvaciones contra conjuros lanzados por criaturas a 5 pies de ti." },
  { n:"Magic Initiate [PHB 2014]", tipo:"General (PHB 2014)", alias:["Magic Initiate [PHB'14]"], d:"Eliges una clase: Bardo, Clérigo, Druida, Hechicero, Brujo o Mago. Aprendes 2 trucos y 1 conjuro de nivel 1 de su lista (con su característica de lanzamiento); puedes lanzar ese conjuro 1 vez por Descanso Largo sin espacio." },
  { n:"Martial Adept [PHB 2014]", tipo:"General (PHB 2014)", a:"O", alias:["Martial Adept [PHB'14]"], d:"Aprendes 2 maniobras del Maestro de Batalla (CD = 8 + comp. + mod. FUE o DES) y ganas 1 dado de superioridad (d6), que recuperas con un Descanso Corto o Largo." },
  { n:"Medium Armor Master [PHB 2014]", tipo:"General (PHB 2014)", alias:["Medium Armor Master [PHB'14]"], d:"Req. competencia con armadura media. La armadura media no te impone Desventaja en Sigilo. Con armadura media puedes sumar hasta +3 (en vez de +2) de tu modificador de DES a la CA." },
  { n:"Mobile [PHB 2014]", tipo:"General (PHB 2014)", alias:["Mobile [PHB'14]"], d:"Tu Velocidad aumenta 10 pies. Cuando realizas la acción Correr, el Terreno Difícil no te cuesta movimiento extra ese turno. Cuando haces un ataque cuerpo a cuerpo a una criatura (impactes o no), no provocas ataques de oportunidad de ella el resto del turno." },
  { n:"Moderately Armored [PHB 2014]", tipo:"General (PHB 2014)", alias:["Moderately Armored [PHB'14]"], d:"Req. competencia con armadura ligera. +1 FUE o DES (máx. 20). Competencia con armadura media y escudos." },
  { n:"Mounted Combatant [PHB 2014]", tipo:"General (PHB 2014)", alias:["Mounted Combatant [PHB'14]"], d:"Ventaja en ataques cuerpo a cuerpo contra criaturas no montadas más pequeñas que tu montura. Puedes obligar a que un ataque dirigido a tu montura te apunte a ti. Si tu montura supera una salvación de DES que reduce el daño a la mitad, no sufre daño; si la falla, sufre la mitad." },
  { n:"Observant [PHB 2014]", tipo:"General (PHB 2014)", alias:["Observant [PHB'14]"], d:"+1 INT o SAB (máx. 20). Si ves la boca de una criatura que habla un idioma que conoces, puedes leerle los labios. +5 a tu Percepción pasiva y a tu Investigación pasiva." },
  { n:"Polearm Master [PHB 2014]", tipo:"General (PHB 2014)", a:"BR", alias:["Polearm Master [PHB'14]"], d:"Si realizas la acción Atacar con una guja, alabarda, bastón o lanza, puedes usar una Acción Adicional para atacar con el extremo opuesto del arma (1d4 contundente, mismo modificador). Mientras empuñas una guja, alabarda, pica, bastón o lanza, las criaturas que entran en tu alcance con esa arma provocan un ataque de oportunidad tuyo." },
  { n:"Resilient [PHB 2014]", tipo:"General (PHB 2014)", d:"Eliges una característica: +1 a ella (máx. 20) y ganas competencia en sus salvaciones." },
  { n:"Ritual Caster [PHB 2014]", tipo:"General (PHB 2014)", alias:["Ritual Caster [PHB'14]"], d:"Req. INT o SAB 13+. Eliges una clase (Bardo, Clérigo, Druida, Hechicero, Brujo o Mago) y consigues un libro de rituales con 2 conjuros de nivel 1 con etiqueta Ritual de su lista. Puedes añadir rituales que encuentres (nivel máximo = la mitad de tu nivel, redondeando hacia arriba; 2 h y 50 po por nivel de conjuro). Sólo puedes lanzarlos como ritual. Característica: INT (Mago), SAB (Clérigo, Druida) o CAR (Bardo, Hechicero, Brujo)." },
  { n:"Sentinel [PHB 2014]", tipo:"General (PHB 2014)", a:"R", alias:["Sentinel [PHB'14]"], d:"Cuando impactas a una criatura con un ataque de oportunidad, su Velocidad pasa a 0 el resto del turno. Las criaturas provocan tus ataques de oportunidad aunque realicen Retirarse. Cuando una criatura a 5 pies de ti ataca a un objetivo que no seas tú, puedes usar tu Reacción para hacerle un ataque cuerpo a cuerpo." },
  { n:"Sharpshooter [PHB 2014]", tipo:"General (PHB 2014)", alias:["Sharpshooter [PHB'14]"], d:"Atacar a largo alcance con armas a distancia no impone Desventaja. Tus ataques a distancia con arma ignoran Cobertura Media y de Tres Cuartos. Antes de atacar con un arma a distancia con la que seas competente, puedes aceptar –5 a la tirada de ataque para infligir +10 de daño si impactas." },
  { n:"Shield Master [PHB 2014]", tipo:"General (PHB 2014)", a:"BR", alias:["Shield Master [PHB'14]"], d:"Si realizas la acción Atacar, puedes usar una Acción Adicional para empujar con tu escudo a una criatura a 5 pies. Sumas el bonificador de CA del escudo a las salvaciones de DES contra efectos que sólo te tengan a ti como objetivo. Si superas una salvación de DES que reduce el daño a la mitad, puedes usar tu Reacción para no sufrir daño." },
  { n:"Skulker [PHB 2014]", tipo:"General (PHB 2014)", alias:["Skulker [PHB'14]"], d:"Req. DES 13+. Puedes intentar esconderte aunque sólo estés ligeramente oscurecido. Si fallas un ataque a distancia con arma desde oculto, no revelas tu posición. La luz tenue no te impone Desventaja en pruebas de Percepción basadas en la vista." },
  { n:"Spell Sniper [PHB 2014]", tipo:"General (PHB 2014)", alias:["Spell Sniper [PHB'14]"], d:"Req. capacidad de lanzar al menos 1 conjuro. Al lanzar un conjuro que requiere tirada de ataque, su alcance se duplica. Tus ataques de conjuro a distancia ignoran Cobertura Media y de Tres Cuartos. Aprendes un truco con tirada de ataque de la lista de una clase a tu elección (con la característica de lanzamiento de esa clase)." },
  { n:"Tavern Brawler [PHB 2014]", tipo:"General (PHB 2014)", a:"B", alias:["Tavern Brawler [PHB'14]"], d:"+1 FUE o CON (máx. 20). Competencia con armas improvisadas. Tus Golpes Desarmados infligen 1d4 + mod. FUE. Cuando impactas con un Golpe Desarmado o un arma improvisada en tu turno, puedes usar una Acción Adicional para intentar agarrar al objetivo." },
  { n:"War Caster [PHB 2014]", tipo:"General (PHB 2014)", a:"R", alias:["War Caster [PHB'14]"], d:"Req. capacidad de lanzar al menos 1 conjuro. Ventaja en salvaciones de CON para mantener la concentración. Puedes hacer componentes somáticos con armas o escudo en las manos. Cuando una criatura provoca tu ataque de oportunidad, puedes usar tu Reacción para lanzarle un conjuro (1 acción, objetivo único)." },
  { n:"Weapon Master [PHB 2014]", tipo:"General (PHB 2014)", alias:["Weapon Master [PHB'14]"], d:"+1 FUE o DES (máx. 20). Competencia con 4 armas simples o marciales a tu elección." },

  /* ════════════════════════════════
     DOTES DE XANATHAR'S GUIDE TO EVERYTHING (XGtE) — con requisito de linaje (2014)
  ════════════════════════════════ */
  { n:"Bountiful Luck [XGtE]", tipo:"General (XGtE)", a:"R", alias:["Bountiful Luck [XGE]"], d:"Req. Mediano. Cuando un aliado que veas a 30 pies saca un 1 en el d20 de un ataque, prueba o salvación, puedes usar tu Reacción para que repita la tirada; debe usar el nuevo resultado." },
  { n:"Dragon Fear [XGtE]", tipo:"General (XGtE)", a:"A", alias:["Dragon Fear [XGE]"], d:"Req. Dracónido. +1 CON, FUE o CAR (máx. 20). En lugar de exhalar con tu Arma de Aliento, puedes rugir: cada criatura que elijas a 30 pies que pueda oírte hace una salvación de SAB (CD 8 + comp. + mod. CAR) o queda Asustada 1 minuto (repite la salvación cuando sufre daño). Gastas un uso del Arma de Aliento." },
  { n:"Dragon Hide [XGtE]", tipo:"General (XGtE)", alias:["Dragon Hide [XGE]"], d:"Req. Dracónido. +1 CON, FUE o CAR (máx. 20). Garras retráctiles: tus ataques desarmados infligen 1d4 + mod. FUE de daño cortante. Escamas: sin armadura, tu CA es 13 + mod. DES." },
  { n:"Drow High Magic [XGtE]", tipo:"General (XGtE)", alias:["Drow High Magic [XGE]"], d:"Req. Elfo (drow). Lanzas Detect Magic a voluntad sin espacio. Lanzas Levitate y Dispel Magic 1 vez cada uno por Descanso Largo sin espacio (Dispel Magic con su nivel mínimo). Característica de lanzamiento: CAR." },
  { n:"Dwarven Fortitude [XGtE]", tipo:"General (XGtE)", alias:["Dwarven Fortitude [XGE]"], d:"Req. Enano. +1 CON (máx. 20). Cuando realizas la acción Esquivar, puedes gastar 1 Dado de Golpe: lo tiras, sumas tu mod. CON (mínimo 1) y recuperas esos PG." },
  { n:"Elven Accuracy [XGtE]", tipo:"General (XGtE)", alias:["Elven Accuracy [XGE]"], d:"Req. Elfo o Semielfo. +1 DES, INT, SAB o CAR (máx. 20). Cuando tienes Ventaja en una tirada de ataque con DES, INT, SAB o CAR, puedes volver a tirar uno de los dados una vez." },
  { n:"Fade Away [XGtE]", tipo:"General (XGtE)", a:"R", alias:["Fade Away [XGE]"], d:"Req. Gnomo. +1 DES o INT (máx. 20). Inmediatamente después de sufrir daño, puedes usar tu Reacción para volverte Invisible hasta el final de tu siguiente turno o hasta que ataques, infligas daño o fuerces una salvación. 1/Descanso Corto o Largo." },
  { n:"Fey Teleportation [XGtE]", tipo:"General (XGtE)", a:"B", alias:["Fey Teleportation [XGE]"], d:"Req. Elfo (alto elfo). +1 INT o CAR (máx. 20). Aprendes Élfico Silvano (Sylvan) y el conjuro Misty Step, que lanzas 1 vez por Descanso Corto o Largo sin espacio (característica: INT)." },
  { n:"Flames of Phlegethos [XGtE]", tipo:"General (XGtE)", alias:["Flames of Phlegethos [XGE]"], d:"Req. Tiefling. +1 INT o CAR (máx. 20). Al tirar daño de fuego de un conjuro, puedes repetir cada 1 y usar el nuevo resultado. Cuando lanzas un conjuro que inflige daño de fuego, puedes envolverte en llamas hasta el final de tu siguiente turno: luz brillante 30 pies y tenue 30 más; quien te impacte con un ataque cuerpo a cuerpo a 5 pies sufre 1d4 de fuego." },
  { n:"Infernal Constitution [XGtE]", tipo:"General (XGtE)", alias:["Infernal Constitution [XGE]"], d:"Req. Tiefling. +1 CON (máx. 20). Resistencia al daño de frío y de veneno. Ventaja en salvaciones para evitar o terminar la condición Envenenado." },
  { n:"Orcish Fury [XGtE]", tipo:"General (XGtE)", a:"O", alias:["Orcish Fury [XGE]"], d:"Req. Semiorco. +1 FUE o CON (máx. 20). Una vez por Descanso Corto o Largo, al impactar con un arma simple o marcial puedes tirar uno de los dados de daño del arma una vez más y sumarlo. Además, justo después de usar Resistencia Implacable puedes usar tu Reacción para hacer un ataque con arma." },
  { n:"Prodigy [XGtE]", tipo:"General (XGtE)", alias:["Prodigy [XGE]"], d:"Req. Humano, Semielfo o Semiorco. Ganas competencia en 1 habilidad, 1 herramienta y 1 idioma a tu elección, y Pericia en 1 habilidad en la que ya seas competente." },
  { n:"Second Chance [XGtE]", tipo:"General (XGtE)", a:"R", d:"Req. Mediano. +1 DES, CON o CAR (máx. 20). Cuando una criatura que veas a 30 pies te impacta con una tirada de ataque, puedes usar tu Reacción para obligarla a repetir la tirada. No puedes volver a usarlo hasta que tires iniciativa o termines un Descanso Corto o Largo." },
  { n:"Squat Nimbleness [XGtE]", tipo:"General (XGtE)", alias:["Squat Nimbleness [XGE]"], d:"Req. Enano o raza Pequeña. +1 FUE o DES (máx. 20). Tu Velocidad aumenta 5 pies. Ganas competencia en Acrobacias o Atletismo. Ventaja en pruebas de Acrobacias o Atletismo para escapar de un agarre." },
  { n:"Wood Elf Magic [XGtE]", tipo:"General (XGtE)", d:"Req. Elfo (elfo del bosque). Aprendes 1 truco de Druida (SAB) y lanzas Longstrider y Pass without Trace 1 vez cada uno por Descanso Largo sin espacio." },

  /* ════════════════════════════════
     DOTES DE TASHA'S CAULDRON OF EVERYTHING (TCE) — exclusivas de 2014 (las demás están fusionadas con su versión PHB 2024)
  ════════════════════════════════ */
  { n:"Artificer Initiate [TCE]", tipo:"General (TCE)", alias:["Artificer Initiate [TCE]"], d:"Aprendes 1 truco y 1 conjuro de nivel 1 de la lista de Artificiero (característica: INT); lanzas el de nivel 1 una vez por Descanso Largo sin espacio (o con espacios). Ganas competencia con 1 tipo de Herramientas de Artesano, que puedes usar como foco para conjuros de Artificiero." },
  { n:"Eldritch Adept [TCE]", tipo:"General (TCE)", alias:["Eldritch Adept [TCE]"], d:"Req. rasgo Lanzamiento de Conjuros o Magia de Pacto. Aprendes 1 Invocación Sobrenatural de Brujo a tu elección (sin requisito de nivel ni de pacto); al subir de nivel puedes sustituirla por otra." },
  { n:"Fighting Initiate [TCE]", tipo:"General (TCE)", alias:["Fighting Initiate [TCE]"], d:"Req. competencia con un arma marcial. Aprendes 1 opción de Estilo de Lucha de la clase Guerrero; al subir de nivel puedes cambiarla por otra." },
  { n:"Gunner [TCE]", tipo:"General (TCE)", alias:["Gunner [TCE]"], d:"+1 DES (máx. 20). Competencia con armas de fuego. Ignoras la propiedad Carga de las armas de fuego. Estar a 5 pies de un enemigo hostil no impone Desventaja a tus ataques a distancia con armas de fuego." },
  { n:"Metamagic Adept [TCE]", tipo:"General (TCE)", alias:["Metamagic Adept [TCE]"], d:"Req. rasgo Lanzamiento de Conjuros o Magia de Pacto. Aprendes 2 opciones de Metamagia del Hechicero y ganas 2 puntos de hechicería para usarlos sólo en Metamagia (los recuperas con un Descanso Largo). Al subir de nivel puedes cambiar una opción por otra." },

  /* ════════════════════════════════
     FIZBAN'S TREASURY OF DRAGONS (FTD) y STRIXHAVEN (SCC)
  ════════════════════════════════ */
  { n:"Gift of the Chromatic Dragon [FTD]", tipo:"General (FTD)", a:"BR", alias:["Gift of the Chromatic Dragon [FTD]"], d:"Req. Nv.4+. Infusión Cromática: 1/Descanso Largo, como Acción Adicional infundes un arma que toques con Ácido, Frío, Fuego, Relámpago o Veneno durante 1 minuto: +1d4 de daño de ese tipo. Resistencia Reactiva: tantas veces por Descanso Largo como tu bonificador de competencia, cuando sufres daño de Ácido, Frío, Fuego, Relámpago o Veneno, usas tu Reacción para obtener Resistencia a ese daño." },
  { n:"Gift of the Gem Dragon [FTD]", tipo:"General (FTD)", a:"R", alias:["Gift of the Gem Dragon [FTD]"], d:"Req. Nv.4+. +1 INT, SAB o CAR (máx. 20). Represalia Telequinética: tantas veces por Descanso Largo como tu bonificador de competencia, cuando una criatura a 10 pies te daña, usas tu Reacción para forzarla a una salvación de FUE (CD 8 + comp. + mod. de la característica aumentada): si falla, sufre 2d8 de daño de fuerza y la empujas hasta 10 pies." },
  { n:"Gift of the Metallic Dragon [FTD]", tipo:"General (FTD)", a:"R", alias:["Gift of the Metallic Dragon [FTD]"], d:"Req. Nv.4+. +1 INT, SAB o CAR (máx. 20). Curación Dracónica: aprendes Cure Wounds y lo lanzas 1 vez por Descanso Largo sin espacio (característica: la que aumentaste). Alas Protectoras: tantas veces por Descanso Largo como tu bonificador de competencia, cuando tú u otra criatura que veas a 5 pies sois impactados por un ataque, usas tu Reacción para sumar tu bonificador de competencia a su CA contra ese ataque." },
  { n:"Strixhaven Initiate [SCC]", tipo:"General (SCC)", alias:["Strixhaven Initiate [SCC]"], d:"Eliges un colegio de Strixhaven (Lorehold, Prismari, Quandrix, Silverquill o Witherbloom). Aprendes 2 trucos y 1 conjuro de nivel 1 de la lista de ese colegio; lanzas el de nivel 1 una vez por Descanso Largo sin espacio (o con espacios). Característica de lanzamiento: INT, SAB o CAR (a tu elección al obtener la dote)." },
];
