/* ══════════════════════════════════════════════════════════
   hechizos-clases.js — Clases que tienen cada conjuro en su lista
   Se usa en el filtro «Clase» del buscador de conjuros.

   Fuente: listas de clase de dnd2024.wikidot.com (reglas 2024) y
   dnd5e.wikidot.com (reglas 2014), descargadas en oct. 2026.
   Criterio (5.5e manda): si el conjuro aparece en alguna lista de
   clase 2024, se usan las clases 2024; si no, las de 2014.
   El Artífice solo existe en 2014: se toma siempre de su lista 2014.
   Conjuros sin clase (hechizos de subclase o especiales): no salen
   al filtrar por una clase concreta.
   Nombres de clase = los del selector de la ficha.
══════════════════════════════════════════════════════════ */

const HECHIZOS_CLASES = {
    acid_splash: ['Artificer', 'Hechicero', 'Mago'],
    blade_ward: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    booming_blade: ['Artificer', 'Brujo', 'Hechicero', 'Mago'],
    chill_touch: ['Brujo', 'Hechicero', 'Mago'],
    control_flames: ['Druida', 'Hechicero', 'Mago'],
    create_bonfire: ['Artificer', 'Brujo', 'Druida', 'Hechicero', 'Mago'],
    dancing_lights: ['Artificer', 'Bardo', 'Hechicero', 'Mago'],
    druidcraft: ['Druida'],
    eldritch_blast: ['Brujo'],
    elementalism: ['Druida', 'Hechicero', 'Mago'],
    fire_bolt: ['Artificer', 'Hechicero', 'Mago'],
    friends: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    frostbite: ['Artificer', 'Brujo', 'Druida', 'Hechicero', 'Mago'],
    green_flame_blade: ['Artificer', 'Brujo', 'Hechicero', 'Mago'],
    guidance: ['Artificer', 'Clérigo', 'Druida'],
    gust: ['Druida', 'Hechicero', 'Mago'],
    hand_of_radiance: ['Clérigo'],
    infestation: ['Brujo', 'Druida', 'Hechicero', 'Mago'],
    light: ['Artificer', 'Bardo', 'Clérigo', 'Hechicero', 'Mago'],
    lightning_lure: ['Artificer', 'Brujo', 'Hechicero', 'Mago'],
    mage_hand: ['Artificer', 'Bardo', 'Brujo', 'Hechicero', 'Mago'],
    magic_stone: ['Artificer', 'Brujo', 'Druida'],
    mending: ['Artificer', 'Bardo', 'Clérigo', 'Druida', 'Hechicero', 'Mago'],
    message: ['Artificer', 'Bardo', 'Druida', 'Hechicero', 'Mago'],
    mind_sliver: ['Brujo', 'Hechicero', 'Mago'],
    minor_illusion: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    mold_earth: ['Druida', 'Hechicero', 'Mago'],
    poison_spray: ['Artificer', 'Brujo', 'Druida', 'Hechicero', 'Mago'],
    prestidigitation: ['Artificer', 'Bardo', 'Brujo', 'Hechicero', 'Mago'],
    produce_flame: ['Druida'],
    primal_savagery: ['Druida'],
    ray_of_frost: ['Artificer', 'Hechicero', 'Mago'],
    resistance: ['Artificer', 'Clérigo', 'Druida'],
    sacred_flame: ['Clérigo'],
    sapping_sting: ['Mago'],
    shape_water: ['Druida', 'Hechicero', 'Mago'],
    shillelagh: ['Druida'],
    shocking_grasp: ['Artificer', 'Hechicero', 'Mago'],
    spare_the_dying: ['Artificer', 'Clérigo', 'Druida'],
    starry_wisp: ['Bardo', 'Druida'],
    sword_burst: ['Artificer', 'Brujo', 'Hechicero', 'Mago'],
    thaumaturgy: ['Clérigo'],
    thorn_whip: ['Artificer', 'Druida'],
    thunderclap: ['Artificer', 'Bardo', 'Brujo', 'Druida', 'Hechicero', 'Mago'],
    toll_the_dead: ['Brujo', 'Clérigo', 'Mago'],
    true_strike: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    vicious_mockery: ['Bardo'],
    virtue: ['Clérigo'],
    word_of_radiance: ['Clérigo'],
    absorb_elements: ['Artificer', 'Druida', 'Explorador', 'Hechicero', 'Mago'],
    alarm: ['Artificer', 'Explorador', 'Mago'],
    animal_friendship: ['Bardo', 'Druida', 'Explorador'],
    armor_of_agathys: ['Brujo'],
    arms_of_hadar: ['Brujo'],
    bane: ['Bardo', 'Brujo', 'Clérigo'],
    beast_bond: ['Druida', 'Explorador'],
    bless: ['Clérigo', 'Paladín'],
    burning_hands: ['Hechicero', 'Mago'],
    catapult: ['Artificer', 'Hechicero', 'Mago'],
    cause_fear: ['Brujo', 'Mago'],
    ceremony: ['Clérigo', 'Paladín'],
    chaos_bolt: ['Hechicero'],
    charm_person: ['Bardo', 'Brujo', 'Druida', 'Hechicero', 'Mago'],
    chromatic_orb: ['Hechicero', 'Mago'],
    color_spray: ['Bardo', 'Hechicero', 'Mago'],
    command: ['Bardo', 'Clérigo', 'Paladín'],
    compelled_duel: ['Paladín'],
    comprehend_languages: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    create_or_destroy_water: ['Clérigo', 'Druida'],
    cure_wounds: ['Artificer', 'Bardo', 'Clérigo', 'Druida', 'Explorador', 'Paladín'],
    detect_evil_and_good: ['Clérigo', 'Paladín'],
    detect_magic: ['Artificer', 'Bardo', 'Brujo', 'Clérigo', 'Druida', 'Explorador', 'Hechicero', 'Mago', 'Paladín'],
    detect_poison_and_disease: ['Clérigo', 'Druida', 'Explorador', 'Paladín'],
    disguise_self: ['Artificer', 'Bardo', 'Hechicero', 'Mago'],
    dissonant_whispers: ['Bardo'],
    divine_favor: ['Paladín'],
    earth_tremor: ['Bardo', 'Druida', 'Hechicero', 'Mago'],
    entangle: ['Druida', 'Explorador'],
    ensnaring_strike: ['Explorador'],
    expeditious_retreat: ['Artificer', 'Brujo', 'Hechicero', 'Mago'],
    faerie_fire: ['Artificer', 'Bardo', 'Druida'],
    false_life: ['Artificer', 'Hechicero', 'Mago'],
    feather_fall: ['Artificer', 'Bardo', 'Hechicero', 'Mago'],
    find_familiar: ['Mago'],
    fog_cloud: ['Druida', 'Explorador', 'Hechicero', 'Mago'],
    frost_fingers: ['Mago'],
    gift_of_alacrity: ['Mago'],
    goodberry: ['Druida', 'Explorador'],
    grease: ['Artificer', 'Hechicero', 'Mago'],
    guiding_bolt: ['Clérigo'],
    hail_of_thorns: ['Explorador'],
    healing_word: ['Bardo', 'Clérigo', 'Druida'],
    hellish_rebuke: ['Brujo'],
    heroism: ['Bardo', 'Paladín'],
    hex: ['Brujo'],
    hunter_mark: ['Explorador'],
    ice_knife: ['Druida', 'Hechicero', 'Mago'],
    identify: ['Artificer', 'Bardo', 'Mago'],
    illusory_script: ['Bardo', 'Brujo', 'Mago'],
    inflict_wounds: ['Clérigo'],
    jump: ['Artificer', 'Druida', 'Explorador', 'Hechicero', 'Mago'],
    longstrider: ['Artificer', 'Bardo', 'Druida', 'Explorador', 'Mago'],
    mage_armor: ['Hechicero', 'Mago'],
    magic_missile: ['Hechicero', 'Mago'],
    magnify_gravity: ['Mago'],
    protection_from_evil: ['Brujo', 'Clérigo', 'Druida', 'Mago', 'Paladín'],
    purify_food_and_drink: ['Artificer', 'Clérigo', 'Druida', 'Paladín'],
    ray_of_sickness: ['Hechicero', 'Mago'],
    sanctuary: ['Artificer', 'Clérigo'],
    searing_smite: ['Paladín'],
    shield: ['Hechicero', 'Mago'],
    shield_of_faith: ['Clérigo', 'Paladín'],
    silent_image: ['Bardo', 'Hechicero', 'Mago'],
    silvery_barbs: ['Bardo', 'Hechicero', 'Mago'],
    sleep: ['Bardo', 'Hechicero', 'Mago'],
    snare: ['Artificer', 'Druida', 'Explorador', 'Mago'],
    speak_with_animals: ['Bardo', 'Brujo', 'Druida', 'Explorador'],
    sudden_awakening: ['Bardo', 'Explorador', 'Hechicero', 'Mago'],
    tashas_caustic_brew: ['Artificer', 'Hechicero', 'Mago'],
    tashas_hideous_laughter: ['Bardo', 'Brujo', 'Mago'],
    tensers_floating_disk: ['Mago'],
    thunderous_smite: ['Paladín'],
    thunderwave: ['Bardo', 'Druida', 'Hechicero', 'Mago'],
    unseen_servant: ['Bardo', 'Brujo', 'Mago'],
    witch_bolt: ['Brujo', 'Hechicero', 'Mago'],
    wrathful_smite: ['Paladín'],
    zephyr_strike: ['Explorador'],
    aganazzars_scorcher: ['Hechicero', 'Mago'],
    aid: ['Artificer', 'Bardo', 'Clérigo', 'Druida', 'Explorador', 'Paladín'],
    air_bubble: ['Artificer', 'Druida', 'Explorador', 'Hechicero', 'Mago'],
    alter_self: ['Artificer', 'Hechicero', 'Mago'],
    animal_messenger: ['Bardo', 'Druida', 'Explorador'],
    arcane_lock: ['Artificer', 'Mago'],
    arcane_vigor: ['Hechicero', 'Mago'],
    augury: ['Clérigo', 'Druida', 'Mago'],
    barkskin: ['Druida', 'Explorador'],
    beast_sense: ['Druida', 'Explorador'],
    blindness_deafness: ['Bardo', 'Clérigo', 'Hechicero', 'Mago'],
    blur: ['Artificer', 'Hechicero', 'Mago'],
    borrowed_knowledge: ['Bardo', 'Brujo', 'Clérigo', 'Mago'],
    calm_emotions: ['Bardo', 'Clérigo'],
    cloud_of_daggers: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    continual_flame: ['Artificer', 'Clérigo', 'Druida', 'Mago'],
    cordon_of_arrows: ['Explorador'],
    crown_of_madness: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    darkness: ['Brujo', 'Hechicero', 'Mago'],
    darkvision: ['Artificer', 'Druida', 'Explorador', 'Hechicero', 'Mago'],
    death_armor: ['Hechicero', 'Mago'],
    deryans_helpful_homunculi: ['Clérigo', 'Mago'],
    detect_thoughts: ['Bardo', 'Hechicero', 'Mago'],
    dragon_breath: ['Hechicero', 'Mago'],
    dust_devil: ['Druida', 'Hechicero', 'Mago'],
    earthbind: ['Brujo', 'Druida', 'Hechicero', 'Mago'],
    elminsters_elusion: ['Mago'],
    enhance_ability: ['Artificer', 'Bardo', 'Clérigo', 'Druida', 'Explorador', 'Hechicero', 'Mago'],
    enlarge_reduce: ['Artificer', 'Bardo', 'Druida', 'Hechicero', 'Mago'],
    enthrall: ['Bardo', 'Brujo'],
    find_steed: ['Paladín'],
    find_traps: ['Clérigo', 'Druida', 'Explorador'],
    flame_blade: ['Druida', 'Hechicero'],
    flaming_sphere: ['Druida', 'Hechicero', 'Mago'],
    fortunes_favor: ['Mago'],
    gentle_repose: ['Clérigo', 'Mago', 'Paladín'],
    gust_of_wind: ['Druida', 'Explorador', 'Hechicero', 'Mago'],
    healing_spirit: ['Druida', 'Explorador'],
    heat_metal: ['Artificer', 'Bardo', 'Druida'],
    hold_person: ['Bardo', 'Brujo', 'Clérigo', 'Druida', 'Hechicero', 'Mago'],
    immovable_object: ['Mago'],
    invisibility: ['Artificer', 'Bardo', 'Brujo', 'Hechicero', 'Mago'],
    kinetic_jaunt: ['Artificer', 'Bardo', 'Hechicero', 'Mago'],
    knock: ['Bardo', 'Hechicero', 'Mago'],
    lesser_restoration: ['Artificer', 'Bardo', 'Clérigo', 'Druida', 'Explorador', 'Paladín'],
    levitate: ['Artificer', 'Hechicero', 'Mago'],
    locate_animals_or_plants: ['Bardo', 'Druida', 'Explorador'],
    locate_object: ['Bardo', 'Clérigo', 'Druida', 'Explorador', 'Mago', 'Paladín'],
    magic_mouth: ['Artificer', 'Bardo', 'Mago'],
    magic_weapon: ['Artificer', 'Explorador', 'Hechicero', 'Mago', 'Paladín'],
    maximilians_earthen_grasp: ['Hechicero', 'Mago'],
    melfs_acid_arrow: ['Mago'],
    mind_spike: ['Brujo', 'Hechicero', 'Mago'],
    mirror_image: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    misty_step: ['Brujo', 'Hechicero', 'Mago'],
    moonbeam: ['Druida'],
    nathairs_mischief: ['Bardo', 'Hechicero', 'Mago'],
    nystuls_magic_aura: ['Mago'],
    pass_without_trace: ['Druida', 'Explorador'],
    phantasmal_force: ['Bardo', 'Hechicero', 'Mago'],
    prayer_of_healing: ['Clérigo', 'Paladín'],
    protection_from_poison: ['Artificer', 'Clérigo', 'Druida', 'Explorador', 'Paladín'],
    pyrotechnics: ['Artificer', 'Bardo', 'Hechicero', 'Mago'],
    ray_of_enfeeblement: ['Brujo', 'Mago'],
    rimes_binding_ice: ['Hechicero', 'Mago'],
    rope_trick: ['Artificer', 'Mago'],
    scorching_ray: ['Hechicero', 'Mago'],
    see_invisibility: ['Artificer', 'Bardo', 'Hechicero', 'Mago'],
    shadow_blade: ['Brujo', 'Hechicero', 'Mago'],
    shatter: ['Bardo', 'Hechicero', 'Mago'],
    shining_smite: ['Paladín'],
    silence: ['Bardo', 'Clérigo', 'Explorador'],
    skywrite: ['Artificer', 'Bardo', 'Druida', 'Mago'],
    snillocs_snowball_swarm: ['Hechicero', 'Mago'],
    spider_climb: ['Artificer', 'Brujo', 'Hechicero', 'Mago'],
    spike_growth: ['Druida', 'Explorador'],
    spiritual_weapon: ['Clérigo'],
    spray_of_cards: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    suggestion: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    summon_beast: ['Druida', 'Explorador'],
    tashas_mind_whip: ['Hechicero', 'Mago'],
    vortex_warp: ['Artificer', 'Hechicero', 'Mago'],
    warding_bond: ['Clérigo', 'Paladín'],
    warding_wind: ['Bardo', 'Druida', 'Hechicero', 'Mago'],
    warp_sense: ['Brujo', 'Hechicero', 'Mago'],
    web: ['Artificer', 'Hechicero', 'Mago'],
    wither_and_bloom: ['Druida', 'Hechicero', 'Mago'],
    wristpocket: ['Mago'],
    zone_of_truth: ['Bardo', 'Clérigo', 'Paladín'],
    animate_dead: ['Clérigo', 'Mago'],
    antagonize: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    ashardalons_stride: ['Artificer', 'Explorador', 'Hechicero', 'Mago'],
    aura_of_vitality: ['Clérigo', 'Druida', 'Paladín'],
    beacon_of_hope: ['Clérigo'],
    bestow_curse: ['Bardo', 'Clérigo', 'Mago'],
    blinding_smite: ['Paladín'],
    blink: ['Artificer', 'Hechicero', 'Mago'],
    cacophonic_shield: ['Bardo', 'Hechicero', 'Mago'],
    call_lightning: ['Druida'],
    catnap: ['Artificer', 'Bardo', 'Hechicero', 'Mago'],
    clairvoyance: ['Bardo', 'Clérigo', 'Hechicero', 'Mago'],
    conjure_animals: ['Druida', 'Explorador'],
    conjure_barrage: ['Explorador'],
    conjure_constructs: ['Mago'],
    counterspell: ['Brujo', 'Hechicero', 'Mago'],
    create_food_and_water: ['Artificer', 'Clérigo', 'Paladín'],
    crusaders_mantle: ['Paladín'],
    daylight: ['Clérigo', 'Druida', 'Explorador', 'Hechicero', 'Paladín'],
    dispel_magic: ['Artificer', 'Bardo', 'Brujo', 'Clérigo', 'Druida', 'Explorador', 'Hechicero', 'Mago', 'Paladín'],
    elemental_weapon: ['Artificer', 'Druida', 'Explorador', 'Paladín'],
    enemies_abound: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    erupting_earth: ['Druida', 'Hechicero', 'Mago'],
    fast_friends: ['Bardo', 'Clérigo', 'Mago'],
    fear: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    feign_death: ['Bardo', 'Clérigo', 'Druida', 'Mago'],
    fireball: ['Hechicero', 'Mago'],
    flame_arrows: ['Artificer', 'Druida', 'Explorador', 'Hechicero', 'Mago'],
    fly: ['Artificer', 'Brujo', 'Hechicero', 'Mago'],
    gaseous_form: ['Brujo', 'Hechicero', 'Mago'],
    glyph_of_warding: ['Artificer', 'Bardo', 'Clérigo', 'Mago'],
    haste: ['Artificer', 'Hechicero', 'Mago'],
    hunger_of_hadar: ['Brujo'],
    hypnotic_pattern: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    incite_greed: ['Brujo', 'Clérigo', 'Hechicero', 'Mago'],
    intellect_fortress: ['Artificer', 'Bardo', 'Brujo', 'Hechicero', 'Mago'],
    laerals_silver_lance: ['Clérigo', 'Hechicero', 'Mago'],
    leomund_tiny_hut: ['Bardo', 'Mago'],
    life_transference: ['Clérigo', 'Mago'],
    lightning_arrow: ['Explorador'],
    lightning_bolt: ['Hechicero', 'Mago'],
    magic_circle: ['Brujo', 'Clérigo', 'Mago', 'Paladín'],
    major_image: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    mass_healing_word: ['Bardo', 'Clérigo'],
    meld_into_stone: ['Clérigo', 'Druida', 'Explorador'],
    melfs_minute_meteors: ['Hechicero', 'Mago'],
    motivational_speech: ['Bardo', 'Clérigo'],
    nondetection: ['Bardo', 'Explorador', 'Mago'],
    phantom_steed: ['Mago'],
    plant_growth: ['Bardo', 'Druida', 'Explorador'],
    protection_from_energy: ['Artificer', 'Clérigo', 'Druida', 'Explorador', 'Hechicero', 'Mago'],
    pulse_wave: ['Mago'],
    remove_curse: ['Brujo', 'Clérigo', 'Mago', 'Paladín'],
    revivify: ['Artificer', 'Clérigo', 'Druida', 'Explorador', 'Paladín'],
    sending: ['Bardo', 'Clérigo', 'Mago'],
    sleet_storm: ['Druida', 'Hechicero', 'Mago'],
    slow: ['Bardo', 'Hechicero', 'Mago'],
    speak_with_dead: ['Bardo', 'Clérigo', 'Mago'],
    speak_with_plants: ['Bardo', 'Druida', 'Explorador'],
    spirit_guardians: ['Clérigo'],
    spirit_shroud: ['Brujo', 'Clérigo', 'Mago', 'Paladín'],
    stinking_cloud: ['Bardo', 'Hechicero', 'Mago'],
    summon_fey: ['Brujo', 'Druida', 'Explorador', 'Mago'],
    summon_lesser_demons: ['Brujo', 'Mago'],
    summon_shadowspawn: ['Brujo', 'Mago'],
    summon_undead: ['Brujo', 'Mago'],
    sylines_viper: ['Druida', 'Mago'],
    thunder_step: ['Brujo', 'Hechicero', 'Mago'],
    tidal_wave: ['Druida', 'Hechicero', 'Mago'],
    tiny_servant: ['Artificer', 'Mago'],
    tongues: ['Bardo', 'Brujo', 'Clérigo', 'Hechicero', 'Mago'],
    vampiric_touch: ['Brujo', 'Hechicero', 'Mago'],
    wall_of_sand: ['Mago'],
    wall_of_water: ['Druida', 'Hechicero', 'Mago'],
    water_breathing: ['Artificer', 'Druida', 'Explorador', 'Hechicero', 'Mago'],
    water_walk: ['Artificer', 'Clérigo', 'Druida', 'Explorador', 'Hechicero'],
    wind_wall: ['Druida', 'Explorador'],
    arcane_eye: ['Artificer', 'Mago'],
    aura_of_life: ['Clérigo', 'Paladín'],
    aura_of_purity: ['Clérigo', 'Paladín'],
    backlash: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    banishment: ['Brujo', 'Clérigo', 'Hechicero', 'Mago', 'Paladín'],
    blight: ['Brujo', 'Druida', 'Hechicero', 'Mago'],
    charm_monster: ['Bardo', 'Brujo', 'Druida', 'Hechicero', 'Mago'],
    compulsion: ['Bardo'],
    confusion: ['Bardo', 'Druida', 'Hechicero', 'Mago'],
    conjure_minor_elementals: ['Druida', 'Mago'],
    conjure_woodland_beings: ['Druida', 'Explorador'],
    control_water: ['Clérigo', 'Druida', 'Mago'],
    death_ward: ['Clérigo', 'Paladín'],
    dimension_door: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    divination: ['Clérigo', 'Druida', 'Mago'],
    dominate_beast: ['Druida', 'Explorador', 'Hechicero'],
    doomtide: ['Bardo', 'Brujo', 'Clérigo'],
    elemental_bane: ['Artificer', 'Brujo', 'Druida', 'Mago'],
    evards_black_tentacles: ['Mago'],
    fabricate: ['Artificer', 'Mago'],
    find_greater_steed: ['Paladín'],
    fire_shield: ['Druida', 'Hechicero', 'Mago'],
    fount_of_moonlight: ['Bardo', 'Druida'],
    freedom_of_movement: ['Artificer', 'Bardo', 'Clérigo', 'Druida', 'Explorador'],
    giant_insect: ['Druida'],
    grasping_vine: ['Druida', 'Explorador'],
    gravity_sinkhole: ['Mago'],
    greater_invisibility: ['Bardo', 'Hechicero', 'Mago'],
    guardian_of_faith: ['Clérigo'],
    guardian_of_nature: ['Druida', 'Explorador'],
    hallucinatory_terrain: ['Bardo', 'Brujo', 'Druida', 'Mago'],
    ice_storm: ['Druida', 'Hechicero', 'Mago'],
    leomund_secret_chest: ['Artificer', 'Mago'],
    locate_creature: ['Bardo', 'Clérigo', 'Druida', 'Explorador', 'Mago', 'Paladín'],
    mordenkainen_faithful_hound: ['Artificer', 'Mago'],
    mordenkainen_private_sanctum: ['Artificer', 'Mago'],
    otiluke_resilient_sphere: ['Artificer', 'Mago'],
    phantasmal_killer: ['Bardo', 'Mago'],
    polymorph: ['Bardo', 'Druida', 'Hechicero', 'Mago'],
    raulothims_psychic_lance: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    shadow_of_moil: ['Brujo'],
    sickening_radiance: ['Brujo', 'Hechicero', 'Mago'],
    spellfire_storm: ['Hechicero', 'Mago'],
    spirit_of_death: ['Brujo', 'Hechicero', 'Mago'],
    staggering_smite: ['Paladín'],
    stone_shape: ['Artificer', 'Clérigo', 'Druida', 'Mago'],
    stoneskin: ['Artificer', 'Druida', 'Explorador', 'Hechicero', 'Mago'],
    storm_sphere: ['Hechicero', 'Mago'],
    summon_aberration: ['Brujo', 'Mago'],
    summon_construct: ['Artificer', 'Mago'],
    summon_elemental: ['Druida', 'Explorador', 'Mago'],
    summon_greater_demon: ['Brujo', 'Mago'],
    vitriolic_sphere: ['Hechicero', 'Mago'],
    wall_of_fire: ['Druida', 'Hechicero', 'Mago'],
    watery_sphere: ['Druida', 'Hechicero', 'Mago'],
    alustriels_mooncloak: ['Bardo', 'Druida', 'Explorador', 'Mago'],
    animate_objects: ['Artificer', 'Bardo', 'Hechicero', 'Mago'],
    antilife_shell: ['Druida'],
    awaken: ['Bardo', 'Druida'],
    banishing_smite: ['Paladín'],
    bigbys_hand: ['Artificer', 'Hechicero', 'Mago'],
    circle_of_power: ['Clérigo', 'Mago', 'Paladín'],
    cloudkill: ['Hechicero', 'Mago'],
    commune: ['Clérigo'],
    commune_with_nature: ['Druida', 'Explorador'],
    cone_of_cold: ['Druida', 'Hechicero', 'Mago'],
    conjure_elemental: ['Druida', 'Mago'],
    conjure_volley: ['Explorador'],
    contact_other_plane: ['Brujo', 'Mago'],
    contagion: ['Clérigo', 'Druida'],
    control_winds: ['Druida', 'Hechicero', 'Mago'],
    create_spelljamming_helm: ['Artificer', 'Mago'],
    creation: ['Artificer', 'Hechicero', 'Mago'],
    danse_macabre: ['Brujo', 'Mago'],
    dawn: ['Clérigo', 'Mago'],
    destructive_wave: ['Paladín'],
    dispel_evil_and_good: ['Clérigo', 'Paladín'],
    dominate_person: ['Bardo', 'Hechicero', 'Mago'],
    dream: ['Bardo', 'Brujo', 'Mago'],
    enervation: ['Brujo', 'Hechicero', 'Mago'],
    far_step: ['Brujo', 'Hechicero', 'Mago'],
    flame_strike: ['Clérigo'],
    geas: ['Bardo', 'Clérigo', 'Druida', 'Mago', 'Paladín'],
    greater_restoration: ['Artificer', 'Bardo', 'Clérigo', 'Druida', 'Explorador', 'Paladín'],
    hallow: ['Clérigo'],
    hold_monster: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    holy_weapon: ['Clérigo', 'Paladín'],
    immolation: ['Hechicero', 'Mago'],
    infernal_calling: ['Brujo', 'Mago'],
    insect_plague: ['Clérigo', 'Druida', 'Hechicero'],
    jallarzis_storm_of_radiance: ['Brujo', 'Mago'],
    legend_lore: ['Bardo', 'Clérigo', 'Mago'],
    maelstrom: ['Druida'],
    mass_cure_wounds: ['Bardo', 'Clérigo', 'Druida'],
    mislead: ['Bardo', 'Brujo', 'Mago'],
    modify_memory: ['Bardo', 'Mago'],
    negative_energy_flood: ['Brujo', 'Mago'],
    passwall: ['Mago'],
    planar_binding: ['Bardo', 'Brujo', 'Clérigo', 'Druida', 'Mago'],
    raise_dead: ['Bardo', 'Clérigo', 'Paladín'],
    rarys_telepathic_bond: ['Bardo', 'Mago'],
    reincarnate: ['Druida'],
    scrying: ['Bardo', 'Brujo', 'Clérigo', 'Druida', 'Mago'],
    seeming: ['Bardo', 'Hechicero', 'Mago'],
    skill_empowerment: ['Artificer', 'Bardo', 'Hechicero', 'Mago'],
    songals_elemental_suffusion: ['Druida', 'Hechicero', 'Mago'],
    steel_wind_strike: ['Explorador', 'Mago'],
    summon_celestial: ['Clérigo', 'Paladín'],
    summon_dragon: ['Mago'],
    swift_quiver: ['Explorador'],
    synaptic_static: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    telekinesis: ['Hechicero', 'Mago'],
    teleportation_circle: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    temporal_shunt: ['Mago'],
    transmute_rock: ['Artificer', 'Druida', 'Mago'],
    tree_stride: ['Druida', 'Explorador'],
    wall_of_force: ['Mago'],
    wall_of_light: ['Brujo', 'Hechicero', 'Mago'],
    wall_of_stone: ['Artificer', 'Druida', 'Hechicero', 'Mago'],
    wrath_of_nature: ['Druida', 'Explorador'],
    yolandes_regal_presence: ['Bardo', 'Mago'],
    arcane_gate: ['Brujo', 'Hechicero', 'Mago'],
    blade_barrier: ['Clérigo'],
    bones_of_the_earth: ['Druida'],
    chain_lightning: ['Hechicero', 'Mago'],
    circle_of_death: ['Brujo', 'Hechicero', 'Mago'],
    conjure_fey: ['Druida'],
    contingency: ['Mago'],
    create_homunculus: ['Mago'],
    create_undead: ['Brujo', 'Clérigo', 'Mago'],
    dirge: ['Bardo', 'Clérigo'],
    disintegrate: ['Hechicero', 'Mago'],
    drawmij_instant_summons: ['Mago'],
    druid_grove: ['Druida'],
    elminsters_effulgent_spheres: ['Druida', 'Hechicero', 'Mago'],
    eyebite: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    find_the_path: ['Bardo', 'Clérigo', 'Druida'],
    fizbans_platinum_shield: ['Hechicero', 'Mago'],
    flesh_to_stone: ['Druida', 'Hechicero', 'Mago'],
    forbiddance: ['Clérigo'],
    globe_of_invulnerability: ['Hechicero', 'Mago'],
    gravity_fissure: ['Mago'],
    guards_and_wards: ['Bardo', 'Mago'],
    harm: ['Clérigo'],
    heal: ['Clérigo', 'Druida'],
    heroes_feast: ['Bardo', 'Clérigo', 'Druida'],
    investiture_of_flame: ['Brujo', 'Druida', 'Hechicero', 'Mago'],
    investiture_of_ice: ['Brujo', 'Druida', 'Hechicero', 'Mago'],
    investiture_of_stone: ['Brujo', 'Druida', 'Hechicero', 'Mago'],
    investiture_of_wind: ['Brujo', 'Druida', 'Hechicero', 'Mago'],
    magic_jar: ['Mago'],
    mass_suggestion: ['Bardo', 'Hechicero', 'Mago'],
    mental_prison: ['Brujo', 'Hechicero', 'Mago'],
    move_earth: ['Druida', 'Hechicero', 'Mago'],
    otherworldly_form: ['Brujo', 'Clérigo', 'Hechicero', 'Mago'],
    otilukes_freezing_sphere: ['Hechicero', 'Mago'],
    ottos_irresistible_dance: ['Bardo', 'Mago'],
    planar_ally: ['Clérigo'],
    primordial_ward: ['Druida'],
    programmed_illusion: ['Bardo', 'Mago'],
    scatter: ['Brujo', 'Hechicero', 'Mago'],
    soul_cage: ['Brujo', 'Mago'],
    summon_fiend: ['Brujo', 'Mago'],
    sunbeam: ['Clérigo', 'Druida', 'Hechicero', 'Mago'],
    tashas_bubbling_cauldron: ['Brujo', 'Mago'],
    tashas_otherworldly_guise: ['Brujo', 'Hechicero', 'Mago'],
    tensers_transformation: ['Mago'],
    transport_via_plants: ['Druida'],
    true_seeing: ['Bardo', 'Brujo', 'Clérigo', 'Hechicero', 'Mago'],
    wall_of_ice: ['Mago'],
    wall_of_thorns: ['Druida'],
    wind_walk: ['Druida'],
    word_of_recall: ['Clérigo'],
    conjure_celestial: ['Clérigo'],
    crown_of_stars: ['Brujo', 'Hechicero', 'Mago'],
    delayed_blast_fireball: ['Hechicero', 'Mago'],
    divine_word: ['Clérigo'],
    draconic_transformation: ['Druida', 'Hechicero', 'Mago'],
    dream_of_the_blue_veil: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    etherealness: ['Bardo', 'Brujo', 'Clérigo', 'Hechicero', 'Mago'],
    finger_of_death: ['Brujo', 'Hechicero', 'Mago'],
    fire_storm: ['Clérigo', 'Druida', 'Hechicero'],
    forcecage: ['Bardo', 'Brujo', 'Mago'],
    mirage_arcane: ['Bardo', 'Druida', 'Mago'],
    mordenkainen_magnificent_mansion: ['Bardo', 'Mago'],
    mordenkainen_sword: ['Bardo', 'Mago'],
    plane_shift: ['Brujo', 'Clérigo', 'Druida', 'Hechicero', 'Mago'],
    power_word_fortify: ['Bardo', 'Clérigo'],
    power_word_pain: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    prismatic_spray: ['Bardo', 'Hechicero', 'Mago'],
    project_image: ['Bardo', 'Mago'],
    regenerate: ['Bardo', 'Clérigo', 'Druida'],
    resurrection: ['Bardo', 'Clérigo'],
    reverse_gravity: ['Druida', 'Hechicero', 'Mago'],
    sequester: ['Mago'],
    simbuls_synostodweomer: ['Hechicero', 'Mago'],
    simulacrum: ['Mago'],
    symbol: ['Bardo', 'Clérigo', 'Druida', 'Mago'],
    teleport: ['Bardo', 'Hechicero', 'Mago'],
    temple_of_the_gods: ['Clérigo'],
    tether_essence: ['Mago'],
    whirlwind: ['Druida', 'Mago'],
    abi_dalzim_horrid_wilting: ['Hechicero', 'Mago'],
    animal_shapes: ['Druida'],
    antimagic_field: ['Clérigo', 'Mago'],
    antipathy_sympathy: ['Bardo', 'Druida', 'Mago'],
    befuddlement: ['Bardo', 'Brujo', 'Druida', 'Mago'],
    clone: ['Mago'],
    control_weather: ['Clérigo', 'Druida', 'Mago'],
    dark_star: ['Mago'],
    demiplane: ['Brujo', 'Hechicero', 'Mago'],
    dominate_monster: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    earthquake: ['Clérigo', 'Druida', 'Hechicero'],
    glibness: ['Bardo', 'Brujo'],
    holy_aura: ['Clérigo'],
    holy_star_of_mystra: ['Clérigo', 'Mago'],
    illusory_dragon: ['Mago'],
    incendiary_cloud: ['Druida', 'Hechicero', 'Mago'],
    maddening_darkness: ['Brujo', 'Mago'],
    maze: ['Mago'],
    mighty_fortress: ['Mago'],
    mind_blank: ['Bardo', 'Mago'],
    power_word_stun: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    reality_break: ['Mago'],
    sunburst: ['Clérigo', 'Druida', 'Hechicero', 'Mago'],
    telepathy: ['Mago'],
    tsunami: ['Druida'],
    astral_projection: ['Brujo', 'Clérigo', 'Mago'],
    blade_of_disaster: ['Brujo', 'Hechicero', 'Mago'],
    foresight: ['Bardo', 'Brujo', 'Druida', 'Mago'],
    gate: ['Brujo', 'Clérigo', 'Hechicero', 'Mago'],
    imprisonment: ['Brujo', 'Mago'],
    invulnerability: ['Mago'],
    mass_heal: ['Clérigo'],
    mass_polymorph: ['Bardo', 'Hechicero', 'Mago'],
    meteor_swarm: ['Hechicero', 'Mago'],
    power_word_heal: ['Bardo', 'Clérigo'],
    power_word_kill: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    prismatic_wall: ['Bardo', 'Mago'],
    psychic_scream: ['Bardo', 'Brujo', 'Hechicero', 'Mago'],
    ravenous_void: ['Mago'],
    shapechange: ['Druida', 'Mago'],
    storm_of_vengeance: ['Druida'],
    time_ravage: ['Mago'],
    time_stop: ['Hechicero', 'Mago'],
    true_polymorph: ['Bardo', 'Brujo', 'Mago'],
    true_resurrection: ['Clérigo', 'Druida'],
    weird: ['Brujo', 'Mago'],
    wish: ['Hechicero', 'Mago'],
};
